name: Global Digitally Built Environment
favicon: null
layout_spectrum: 0.570967068662867
typography_spectrum: 0.43279459816403687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.27124223951250315
  lightness: 0.5804962385445833
  saturation: 0.3113514785654843
  rhythmicContrast: 0.6258858321234584
purpose: []
