name: Global Digitally Built Environment
favicon: null
layout_spectrum: 0.92414
typography_spectrum: 0.89517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99b52c'
    - '#c0de86'
    - '#e7f2d2'
    - '#b3c862'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.6258858321234584
purpose: []
